---
title: "연령대에 따른 월급 차이"
author: 오유리
date: July 30, 2020
output: github_document
---

```{r, include=F}
library(foreign)             # SPSS 파일 로드
library(dplyr)               # 전처리
library(ggplot2)             # 시각화
library(readxl)              # 엑셀 파일 불러오기

# 데이터 불러오기
raw_welfare <- read.spss(file = "Koweps_hpc10_2015_beta1.sav",
                         to.data.frame = T)

# 복사본 만들기
welfare <- raw_welfare

# 변수 이름 변경하기기
welfare <- rename(welfare,
                  sex = h10_g3,            # 성별
                  birth = h10_g4,          # 태어난 연도
                  marriage = h10_g10,      # 혼인 상태
                  religion = h10_g11,      # 종교
                  income = p1002_8aq1,     # 월급
                  code_job = h10_eco9,     # 직종 코드
                  code_region = h10_reg7)  # 지역 코드


#birth 이상치 결측 처리
welfare$birth <- ifelse(welfare$birth == 9999, NA, welfare$birth)

#나이 파생변수 만들기
welfare$age <- 2015 - welfare$birth + 1

```

## 4. 연령대에 따른 월급 차이

### 분석 절차

### 연령대 변수 검토 및 전처리하기

#### 1. 파생변수 만들기 - 연령대

연령대와 월급 변수를 가지고 연령대별 월급 평균표와 그래프를 만든다.
나이 변수를 연령대 변수로 만든다. 각 범주에 몇 명이 있는지 본다.
```{r}

welfare<- welfare %>% 
  mutate(ageg = ifelse(age<30, "young", ifelse(age <= 59, "middle","old")))

table(welfare$ageg)

qplot(welfare$ageg)

```

### 연령대에 따른 월급 차이 분석하기

#### 1. 연령대별 월급 평균표 만들기

월급 변수 전처리는 이미 완료 했으니 생략한다.
분석 결과를 보면 월급 평균이 초년 163만 원, 중년 281만 원, 노년 125만 원이다.

```{r, message=F}

ageg_income <- welfare %>% 
  filter(!is.na(income)) %>% 
  group_by(ageg) %>% 
  summarise(mean_income = mean(income))

ageg_income

```
#### 2. 그래프 만들기

```{r}
ggplot(data = ageg_income, aes(x = ageg, y = mean_income)) + geom_col()

```
#### 막대 정렬 : 초년, 중년, 노년 나이 순

ggplot은 막대를 변수의 알파벳 순으로 정렬하도록 기본값이 설정되어 있다. 막대가 초년, 중년, 노년의 나이 순으로 정렬되도록 설정한다. 

결과를 보면 중년이 가장 많이 받는걸 알 수 있다. 

```{r}
ggplot(data = ageg_income, aes(x = ageg,y = mean_income)) + geom_col() + scale_x_discrete(limits = c("young", "middle","old"))


```
